/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package prograproyecto;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class ModificarVehiculo extends javax.swing.JPanel {

    private principal mainApp;
    private String placaOriginal;
    
    public ModificarVehiculo(principal mainApp, String placa, String modelo, String marca, String anio) {
        initComponents();
        this.mainApp = mainApp;
        this.placaOriginal = placa;

        ModificaModelo.setText(modelo);
        ModificaMarca.setText(marca);
        ModificaAnio.setText(anio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Anio = new javax.swing.JLabel();
        GuardarDatos = new javax.swing.JButton();
        ModificaModelo = new javax.swing.JTextField();
        ModificaMarca = new javax.swing.JTextField();
        Modelo = new javax.swing.JLabel();
        ModificaAnio = new javax.swing.JTextField();
        Marca = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        Anio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Anio.setText("Año:");

        GuardarDatos.setText("Guardar");
        GuardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarDatosActionPerformed(evt);
            }
        });

        ModificaModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaModeloActionPerformed(evt);
            }
        });

        ModificaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaMarcaActionPerformed(evt);
            }
        });

        Modelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Modelo.setText("Modelo Vehiculo:");

        ModificaAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaAnioActionPerformed(evt);
            }
        });

        Marca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Marca.setText("Marca Vehiculo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Modelo)
                    .addComponent(Marca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ModificaModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(ModificaMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Anio)
                .addGap(18, 18, 18)
                .addComponent(ModificaAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(GuardarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Modelo)
                            .addComponent(ModificaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Anio)
                            .addComponent(ModificaAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModificaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Marca))
                .addGap(39, 39, 39)
                .addComponent(GuardarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarDatosActionPerformed
        String nuevoModelo = ModificaModelo.getText().trim();
    String nuevaMarca = ModificaMarca.getText().trim();
    String nuevoAnioStr = ModificaAnio.getText().trim();

    if (nuevoModelo.isEmpty() || nuevaMarca.isEmpty() || nuevoAnioStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Completa todos los campos.");
        return;
    }

    int nuevoAnio;
    try {
        nuevoAnio = Integer.parseInt(nuevoAnioStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Año inválido.");
        return;
    }

    File carpeta = mainApp.getCarpetaSeleccionada();
    String dep = mainApp.getDepartamentoSeleccionado();
    File archivo = new File(carpeta, dep + "/" + dep + "_vehiculos.txt");

    try {
        // Leer todas las líneas del archivo
        java.util.List<String> lineas = new java.util.ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split(",");
                if (datos.length >= 6 && datos[0].equalsIgnoreCase(placaOriginal)) {
                    datos[3] = nuevaMarca;
                    datos[4] = nuevoModelo;
                    datos[5] = String.valueOf(nuevoAnio);
                    linea = String.join(",", datos);
                }
                lineas.add(linea);
            }
        }

        // Reescribir el archivo con las líneas modificadas
        try (FileWriter fw = new FileWriter(archivo, false)) {
            for (String l : lineas) {
                fw.write(l + "\n");
            }
        }

        JOptionPane.showMessageDialog(this, "Vehículo modificado correctamente.");
        mainApp.recargarTabla();
        setVisible(false);

    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al modificar el archivo.");
    }

    }//GEN-LAST:event_GuardarDatosActionPerformed

    private void ModificaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificaMarcaActionPerformed

    private void ModificaModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificaModeloActionPerformed

    private void ModificaAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificaAnioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Anio;
    private javax.swing.JButton GuardarDatos;
    private javax.swing.JLabel Marca;
    private javax.swing.JLabel Modelo;
    private javax.swing.JTextField ModificaAnio;
    private javax.swing.JTextField ModificaMarca;
    private javax.swing.JTextField ModificaModelo;
    // End of variables declaration//GEN-END:variables
}
