/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package prograproyecto;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class NuevoVehiculo extends javax.swing.JPanel {

    private principal mainApp;
    
    public NuevoVehiculo(principal mainApp) {
        initComponents();
         this.mainApp = mainApp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Placa = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Modelo = new javax.swing.JLabel();
        Marca = new javax.swing.JLabel();
        DPI = new javax.swing.JLabel();
        Anio = new javax.swing.JLabel();
        MultasNuevoV = new javax.swing.JLabel();
        TraspasoNuevoV = new javax.swing.JLabel();
        NuevaPlaca = new javax.swing.JTextField();
        NombreNuevo = new javax.swing.JTextField();
        NuevoModelo = new javax.swing.JTextField();
        NuevaMarca = new javax.swing.JTextField();
        NuevoDPI = new javax.swing.JTextField();
        NuevoAnio = new javax.swing.JTextField();
        MultaVehiculoNuevo = new javax.swing.JTextField();
        TraspasoVehiculoNuevo = new javax.swing.JTextField();
        DepartamentoNuevo = new javax.swing.JLabel();
        ElegirDep = new javax.swing.JComboBox<>();
        GuardarDatos = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 255, 51));

        Placa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Placa.setText("Placa:");

        Nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Nombre.setText("Nombre Propietario:");

        Modelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Modelo.setText("Modelo Vehiculo:");

        Marca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Marca.setText("Marca Vehiculo:");

        DPI.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DPI.setText("DPI:");

        Anio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Anio.setText("Año:");

        MultasNuevoV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MultasNuevoV.setText("Multas:");

        TraspasoNuevoV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TraspasoNuevoV.setText("Traspasos:");

        NuevaPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaPlacaActionPerformed(evt);
            }
        });

        NuevoDPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoDPIActionPerformed(evt);
            }
        });

        DepartamentoNuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DepartamentoNuevo.setText("Departamento:");

        ElegirDep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        GuardarDatos.setText("Guardar");
        GuardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Placa)
                    .addComponent(Nombre)
                    .addComponent(Modelo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(DepartamentoNuevo)
                        .addComponent(Marca)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ElegirDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)
                        .addComponent(GuardarDatos))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(NuevaMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(NuevaPlaca, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreNuevo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NuevoModelo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(TraspasoNuevoV))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Anio, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DPI, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(MultasNuevoV, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(TraspasoVehiculoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(NuevoAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(NuevoDPI, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(MultaVehiculoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Placa)
                                    .addComponent(NuevaPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(DPI)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nombre)
                            .addComponent(NombreNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Anio)
                            .addComponent(NuevoAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(NuevoDPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modelo)
                    .addComponent(NuevoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MultasNuevoV)
                    .addComponent(MultaVehiculoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TraspasoNuevoV)
                    .addComponent(Marca)
                    .addComponent(NuevaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TraspasoVehiculoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DepartamentoNuevo)
                            .addComponent(ElegirDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(GuardarDatos)
                        .addGap(26, 26, 26))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NuevaPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevaPlacaActionPerformed

    public void setDepartamentos(List<String> departamentos) {
    ElegirDep.removeAllItems();
    for (String dep : departamentos) {
        ElegirDep.addItem(dep);
    }
}

    
    private void GuardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarDatosActionPerformed
        String placa = NuevaPlaca.getText().trim();
    String dpi = NuevoDPI.getText().trim();
    String nombre = NombreNuevo.getText().trim();
    String marca = NuevaMarca.getText().trim();
    String modelo = NuevoModelo.getText().trim();
    int anio = Integer.parseInt(NuevoAnio.getText().trim());
    int multas = Integer.parseInt(MultaVehiculoNuevo.getText().trim());
    int traspasos = Integer.parseInt(TraspasoVehiculoNuevo.getText().trim());
    String departamento = (String) ElegirDep.getSelectedItem();

    String[] datos = {placa, dpi, nombre, marca, modelo, String.valueOf(anio), String.valueOf(multas), String.valueOf(traspasos)};
    Vehiculo nuevo = new Vehiculo(datos, departamento);

    mainApp.abb.insertar(nuevo);
    mainApp.avl.insertar(nuevo);
    File carpeta = mainApp.carpetaSeleccionada;

    File archivo = new File(carpeta, departamento + "/" + departamento + "_vehiculos.txt");
    System.out.println("Intentando guardar en: " + archivo.getAbsolutePath());
    System.out.println("Existe carpeta: " + carpeta.exists());
    System.out.println("Existe archivo: " + archivo.exists());

    try (FileWriter fw = new FileWriter(archivo, true)) {
        fw.write(String.join(",", datos) + "\n");
        JOptionPane.showMessageDialog(this, "Vehículo agregado correctamente.");
    } catch (IOException ex) {
         ex.printStackTrace(); 
    JOptionPane.showMessageDialog(this, "Error al guardar en archivo: " + ex.getMessage());
    }

    this.setVisible(false); 
    
    
    }//GEN-LAST:event_GuardarDatosActionPerformed

    private void NuevoDPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoDPIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoDPIActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Anio;
    private javax.swing.JLabel DPI;
    private javax.swing.JLabel DepartamentoNuevo;
    private javax.swing.JComboBox<String> ElegirDep;
    private javax.swing.JButton GuardarDatos;
    private javax.swing.JLabel Marca;
    private javax.swing.JLabel Modelo;
    private javax.swing.JTextField MultaVehiculoNuevo;
    private javax.swing.JLabel MultasNuevoV;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField NombreNuevo;
    private javax.swing.JTextField NuevaMarca;
    private javax.swing.JTextField NuevaPlaca;
    private javax.swing.JTextField NuevoAnio;
    private javax.swing.JTextField NuevoDPI;
    private javax.swing.JTextField NuevoModelo;
    private javax.swing.JLabel Placa;
    private javax.swing.JLabel TraspasoNuevoV;
    private javax.swing.JTextField TraspasoVehiculoNuevo;
    // End of variables declaration//GEN-END:variables
}
